/// Flutter icons EIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EIcons
///      fonts:
///       - asset: fonts/EIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EIcons {
  EIcons._();

  static const _kFontFam = 'EIcons';
  static const String? _kFontPkg = null;

  static const IconData ap_connected = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ap_connrect = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox_circle_fill = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox_circle_line = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sta_connect = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geo = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reconfig = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sta_connected = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reconfigure = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
